### ISSUE TITLE
Бублик не запускается, если в имени схемы присутствует дефис (Postgres to Postgres flow)

### ISSUE THREAD

**Issue by SergeyTheHuman** [dimarudik/bublik#26]
## Описание
Столкнулся со странной проблемой при попытке перелить данные из схемы, в которой есть дефис

Варианты, которые пробовал:
- `"fromSchemaName": "main-page"` - ошибка синтаксиса SQL при запуске бублика ([log_with_no_external_quotes.log](https://github.com/user-attachments/files/19126503/log_with_no_external_quotes.log))
- `"fromSchemaName": "\"main-page\""` - таблица не найдена ([log_with_external_quotes.log](https://github.com/user-attachments/files/19126505/log_with_external_quotes.log))
- `"fromSchemaName": "main\-page"` - ошибка при парсинге конфига ([log_with_single_slash.log](https://github.com/user-attachments/files/19126504/log_with_single_slash.log))

## Config
```yaml
threadCount: 10

fromProperties:
   url: jdbc:postgresql://finanalytics-sme-financial-analytics-1.ds.pg-test.tcsbank.ru:5432/finanalytics_qa
   user: finanalytics_qa
   password: спрятано_от_лишних_глаз
toProperties:
   url: jdbc:postgresql://faq-schema-sme-financial-analytics-1.ix.pg-test.tcsbank.ru:5432/faq_schema
   user: faq_schema
   password: спрятано_от_лишних_глаз
```

## Mapping
```JSON
[
    {
        "fromSchemaName": "main-page",
        "fromTableName": "page_schemas",
        "toSchemaName": "schema",
        "toTableName": "page_schemas",
        "fromTaskName": "page_schemas_task_7",
        "fetchWhereClause": "1 = 1",
        "columnToColumn": {
            "name": "name",
            "schema": "schema",
            "timestamp": "timestamp"
        }
    }
]
```
